# Generated by Django 6.1 on 2026-08-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelstation',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
