# Generated by Django 6.1 on 2026-08-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_rename_modified_fuelstation_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('observed_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='fuelstation',
            name='stations_fu_state_5f6afa_idx',
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stations.fuelstation'),
        ),
        migrations.RemoveField(
            model_name='fuelstation',
            name='price',
        ),
        migrations.AddIndex(
            model_name='fuelprice',
            index=models.Index(fields=['station', '-observed_at'], name='station_latest_price_idx'),
        ),
    ]
