# Generated by Django 6.1 on 2026-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_location', models.CharField(max_length=255)),
                ('finish_location', models.CharField(max_length=255)),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('finish_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('finish_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('route_distance_miles', models.FloatField()),
                ('route_geometry', models.JSONField()),
                ('fuel_total_purchased_gallons', models.FloatField()),
                ('fuel_total_consumed_gallons', models.FloatField()),
                ('fuel_remaining_gallons', models.FloatField()),
                ('fuel_total_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fuel_stops', models.JSONField()),
                ('price_fingerprint', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('start_location', 'finish_location'), name='unique_route_cache')],
            },
        ),
    ]
